### ISSUE TITLE
KeyError: "word 'look' not in vocabulary"

### ISSUE THREAD

**Issue by qiu-nian** [Kyubyong/bert-token-embeddings#1]
Code and error are as follows：
`import gensim`
`f = "bert-base-uncased.30522.768d.vec" `
`model = gensim.models.KeyedVectors.load_word2vec_format(f, binary=True)`
`print(model.most_similar(["look"]))`
D:\Anaconda2\envs\book_py36_pytorch\lib\site-packages\gensim\models\keyedvectors.py:2333: RuntimeWarning: overflow encountered in square  dist = sqrt((m ** 2).sum(-1))[..., newaxis]
Traceback (most recent call last):
  File `"<input>"`, line 5, in <module>
  File "D:\Anaconda2\envs\book_py36_pytorch\lib\site-packages\gensim\models\keyedvectors.py", line 543, in most_similar mean.append(weight * self.word_vec(word, use_norm=True))
  File "D:\Anaconda2\envs\book_py36_pytorch\lib\site-packages\gensim\models\keyedvectors.py", line 464, in word_vec
    raise KeyError("word '%s' not in vocabulary" % word)
KeyError: "word 'look' not in vocabulary"

**Comment by qiu-nian** [comment]
@Kyubyong

**Comment by qiu-nian** [comment]
In the saved word vector, there will be cases where the length of the word vector is different, some are 768, and some are 769. This is the reason for the above error.
The reason why the length of the word vector is different is that there is one more space before the positive number in the vector, that is, the space between two characters is two.
